package com.lezic.app.sys.crud.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import com.lezic.core.crud.annotation.WebField;

/**
 * SysUser generated by codeTool
 * 
 * @author cielo
 * @date 2016-01-26 15:03:54
 */
@Entity
@Table(name = "sys_crud")
public class SysCrud implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@Column(name = "id", length = 36, unique = true, nullable = false)
	@WebField(label = "", placeholder = "请输入", rules = "required;length(~36);", length = 36, unique = true, nullable = false)
	private String id;

	@Column(name = "TABLE_NAME", length = 255, nullable = false)
	@WebField(label = "表名", placeholder = "请输入表名", rules = "required;length(~255);", length = 255, nullable = false)
	private String tableName;

	@Column(name = "ENTITY_NAME", length = 255, nullable = false)
	@WebField(label = "实体类名", placeholder = "请输入实体类名", rules = "required;length(~255);", length = 255, nullable = false)
	private String entityName;

	@Column(name = "MODULE_CODE", length = 255, nullable = false)
	@WebField(label = "模块代码", placeholder = "请输入模块代码", rules = "required;length(~255);", length = 255, nullable = false)
	private String moduleCode;

	@Column(name = "MODULE_NAME", length = 255, nullable = false)
	@WebField(label = "模块名", placeholder = "请输入模块名", rules = "required;length(~255);", length = 255, nullable = false)
	private String moduleName;

	@Column(name = "REQUEST_MAPPING", length = 255, nullable = false)
	@WebField(label = "请求映射路径", placeholder = "请输入请求映射路径", rules = "required;length(~255);", length = 255, nullable = false)
	private String requestMapping;

	@Column(name = "LIST_PAGE", length = 255, nullable = false)
	@WebField(label = "列表页面", placeholder = "请输入列表页面", rules = "required;length(~255);", length = 255, nullable = false)
	private String listPage;

	@Column(name = "ADD_PAGE", length = 255, nullable = false)
	@WebField(label = "新增页面", placeholder = "请输入新增页面", rules = "required;length(~255);", length = 255, nullable = false)
	private String addPage;

	@Column(name = "UPD_PAGE", length = 255, nullable = false)
	@WebField(label = "修改页面", placeholder = "请输入修改页面", rules = "required;length(~255);", length = 255, nullable = false)
	private String updPage;

	@Column(name = "OP_USER_ID", length = 36)
	@WebField(label = "", placeholder = "请输入", rules = "length(~36);", length = 36)
	private String opUserId;

	@Column(name = "OP_TIME", length = 0)
	@WebField(label = "", placeholder = "请输入", rules = "", length = 0)
	private Date opTime;

	/**
	 * 设置
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * 获取
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * 设置 表名
	 */
	public void setTableName(String tableName) {
		this.tableName = tableName;
	}

	/**
	 * 获取 表名
	 */
	public String getTableName() {
		return this.tableName;
	}

	/**
	 * 设置 实体类名
	 */
	public void setEntityName(String entityName) {
		this.entityName = entityName;
	}

	/**
	 * 获取 实体类名
	 */
	public String getEntityName() {
		return this.entityName;
	}

	/**
	 * 设置 模块代码
	 */
	public void setModuleCode(String moduleCode) {
		this.moduleCode = moduleCode;
	}

	/**
	 * 获取 模块代码
	 */
	public String getModuleCode() {
		return this.moduleCode;
	}

	/**
	 * 设置 模块名
	 */
	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}

	/**
	 * 获取 模块名
	 */
	public String getModuleName() {
		return this.moduleName;
	}

	/**
	 * 设置 请求映射路径
	 */
	public void setRequestMapping(String requestMapping) {
		this.requestMapping = requestMapping;
	}

	/**
	 * 获取 请求映射路径
	 */
	public String getRequestMapping() {
		return this.requestMapping;
	}

	/**
	 * 设置 列表页面
	 */
	public void setListPage(String listPage) {
		this.listPage = listPage;
	}

	/**
	 * 获取 列表页面
	 */
	public String getListPage() {
		return this.listPage;
	}

	/**
	 * 设置 新增页面
	 */
	public void setAddPage(String addPage) {
		this.addPage = addPage;
	}

	/**
	 * 获取 新增页面
	 */
	public String getAddPage() {
		return this.addPage;
	}

	/**
	 * 设置 修改页面
	 */
	public void setUpdPage(String updPage) {
		this.updPage = updPage;
	}

	/**
	 * 获取 修改页面
	 */
	public String getUpdPage() {
		return this.updPage;
	}

	/**
	 * 设置
	 */
	public void setOpUserId(String opUserId) {
		this.opUserId = opUserId;
	}

	/**
	 * 获取
	 */
	public String getOpUserId() {
		return this.opUserId;
	}

	/**
	 * 设置
	 */
	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	/**
	 * 获取
	 */
	public Date getOpTime() {
		return this.opTime;
	}

}
